import pytest


@pytest.fixture(autouse=True)
def set_test_env(monkeypatch):
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")
    monkeypatch.setenv("OPENAI_API_BASE", "https://api.openai.com/v1")
    monkeypatch.setenv("REDIS_URL", "redis://localhost:6379/0")
    monkeypatch.setenv("MODEL_NAME", "gpt-test")
    monkeypatch.setenv("MILVUS_URI", "http://localhost:19530")
    monkeypatch.setenv("NEO4J_URI", "bolt://localhost:7687")
    monkeypatch.setenv("NEO4J_USER", "neo4j")
    monkeypatch.setenv("NEO4J_PASSWORD", "password")
    monkeypatch.setenv("DATABASE_URL", "postgresql://cloudagent:cloudagent@localhost:5432/cloudagent")
    monkeypatch.setenv("JWT_DISABLED", "true")
    monkeypatch.setenv("RATE_LIMIT_REQUESTS_PER_MINUTE", "60")
    monkeypatch.setenv("CIRCUIT_BREAKER_FAILURE_THRESHOLD", "5")
    monkeypatch.setenv("CIRCUIT_BREAKER_RECOVERY_TIMEOUT", "60")
    monkeypatch.setenv("ENABLE_METRICS", "true")
    monkeypatch.setenv("DEFAULT_TENANT_ID", "default")
    monkeypatch.setenv("MCP_SERVERS", "order,sms,ticket")
    monkeypatch.setenv("ORDER_SERVICE_URL", "")
    monkeypatch.setenv("SMS_SERVICE_URL", "")
    monkeypatch.setenv("TICKET_SERVICE_URL", "")
    monkeypatch.setenv("ENABLE_SSE", "true")
    monkeypatch.setenv("CORS_ORIGINS", "http://localhost:5173")
